### ISSUE TITLE
Add Pangeo Gallery to the external links gallery

### ISSUE THREAD

**Issue by andersy005** [ProjectPythia/projectpythia.github.io#106]
Make sure the following items are specified :

- `url`
- `title`
- `description`
- `authors` (please credit the creators of the resource in at least one method (`name`, `affiliation`, `affiliation_url`, or `email`)
- `tag` (at least one tag is required, this helps users access the link by searching via the relevant `packages`, `formats`, or `domains`)

```yaml
---
url: 'http://gallery.pangeo.io' # The URL link to the resource you are submitting.
thumbnail: 'https://github.com/pangeo-data/pangeo/raw/master/docs/_static/pangeo_simple_logo.png' # The URL link to the thumbnail image associated with this resource.
title: 'Pangeo Gallery' # The title of the resource.
description: 'A gallery of different Pangeo use cases' # A brief description of the resource.
authors: # Mulitiple authors are supported, add each author separately.
  - name: 'Pangeo Community' # The name of the first author.
    affiliation: 'Pangeo' # The affiliation of the authors / first author (more appropriate than name if a large team worked on the resource).
    affiliation_url: 'http://pangeo.io/' # The URL link to the affiliation website.

tags: # Replace or delete the "unspecified" tag for each section with keywords associated with the resource. 
  packages:
    - jupyter
    - xarray
    - dask
    - matplotlib
    - intake
    - xgcm
    - holoviews
    - pandas
    - numpy
  formats:
    - gallery
    - tutorial
  domains:
    - glaciology
    - remote-sensing
    - physical-oceanography
    - hydrology
---

```
