### ISSUE TITLE
Add PyAOS Data Carpentry lessons?

### ISSUE THREAD

**Issue by DamienIrving** [ProjectPythia/projectpythia.github.io#127]
```yaml
---
url: 'https://carpentrieslab.github.io/python-aos-lesson/' # The URL link to the resource you are submitting.
thumbnail: '/_static/thumbnails/DC_logo_vision.png' # The URL link to the thumbnail image associated with this resource.
title: 'Python for Atmosphere and Ocean Science' # The title of the resource.
description: 'Lesson materials for a one-day workshop on using Python in the atmosphere and ocean sciences. Useful for any geoscientist working with raster (a.k.a. “gridded”) data, the lessons cover packages/tools including conda, xarray, dask and netCDF, as well as best practices including functions, command line programs, defensive programming, provenance tracking and version control via git/GitHub.' # A brief description of the resource.
authors: # Mulitiple authors are supported, add each author separately.
  - name: '' # The name of the first author.
    affiliation: 'Data Carpentry' # The affiliation of the authors / first author (more appropriate than name if a large team worked on the resource).
    affiliation_url: 'https://datacarpentry.org/' # The URL link to the affiliation website.
    email: '' # The author's email, if publically available.
  - name: '' # The name of the second+ author.
    affiliation: ''
    affiliation_url: ''
    email: ''
tags: # Replace or delete the "unspecified" tag for each section with keywords associated with the resource. Multi-word tags should be entered with a space between the words (i.e. not joined with a `-`).
  packages:
    - xarray
    - dask
    - cartopy
    - numpy
    - matplotlib
  formats:
    - course
  domains:
    - atmospheric science
    - climate science
---

```

These lessons have been used for workshops at/for [AMOS](https://www.amos.org.au/), [AMS](https://www.ametsoc.org/index.cfm/ams/), [WHOI](https://www.whoi.edu/), [NOAA](https://www.noaa.gov/), [Australian Bureau of Meteorology](http://www.bom.gov.au/), [NIWA](https://niwa.co.nz/), etc and are being taught by a growing community of Carpentries instructors who study/work in the geosciences. See the project [README](https://github.com/carpentrieslab/python-aos-lesson#python-for-atmosphere-and-ocean-scientists) for details.
