### ISSUE TITLE
Python for Geosciences

### ISSUE THREAD

**Issue by koldunovn** [ProjectPythia/projectpythia.github.io#152]
You might be interested to add this one :) More detailed description is in the README of the repository.
```yaml
---
url: 'https://github.com/koldunovn/python_for_geosciences' # The URL link to the resource you are submitting.
thumbnail: '' # The URL link to the thumbnail image associated with this resource.
title: 'Python for Geosciences' # The title of the resource.
description: 'This is a short overview of how Python is used in science and particularly in geosciences targeting people who already know programming (e.g. Matlab). ' # A brief description of the resource.
authors: # Mulitiple authors are supported, add each author separately.
  - name: 'Nikolay Koldunov' # The name of the first author.
    affiliation: 'Alfred Wegener Institute for Polar and Marine Research ' # The affiliation of the authors / first author (more appropriate than name if a large team worked on the resource).
    affiliation_url: 'https://www.awi.de/en/' # The URL link to the affiliation website.
    email: 'koldunovn@gmail.com' # The author's email, if publically available.
tags: # Replace or delete the "unspecified" tag for each section with keywords associated with the resource. Multi-word tags should be entered with a space between the words (i.e. not joined with a `-`).
  packages:
      - matplotlib
      - scipy
      - pandas
      - xarray
      - cartopy
  formats:
    - course 
    - tutorial
    - video
  domains:
    - atmospheric science
    - climate science
    - physical oceanography
    - data science
---

```
