### ISSUE TITLE
Add Environmental Data Science Book to the Resource Gallery

### ISSUE THREAD

**Issue by acocac** [ProjectPythia/projectpythia.github.io#279]
```yaml
---
url: 'https://github.com/alan-turing-institute/environmental-ds-book' # The URL link to the resource you are submitting.
thumbnail: 'https://raw.githubusercontent.com/alan-turing-institute/environmental-ds-book/master/book/figures/logo/logo.png' # The URL link to the thumbnail image associated with this resource.
title: 'Environmental Data Science Book' # The title of the resource.
description: 'A living, open and community-driven resource to showcase and support computational notebooks for collaborative, reproducible and transparent Environmental Science' # A brief description of the resource.
authors: # Mulitiple authors are supported, add each author separately.
  - name: 'EDS book community' # The name of the first author.
    institution: 'Environmental Data Science Book' # The institution of the authors / first author (more appropriate than name if a large team worked on the resource).
    institution_url: 'https://github.com/alan-turing-institute/environmental-ds-book#contributors' # The URL link to the institution website.
    email: 'environmental.ds.book@gmail.com' # The author's email, if publically available.
tags: # Replace or delete the "unspecified" tag for each section with keywords associated with the resource. Multi-word tags should be entered with a space between the words (i.e. not joined with a `-`).
  packages:
    - pangeo
    - pooch
    - intake
    - pystac
    - pandas
    - geopandas
    - xarray
    - dask
    - matplotlib
    - holoviews
    - cartopy
  formats:
    - book
    - gallery
  domains:
    - environmental science
    - climate science
    - ecology
    - hydrology
    - physical geography
    - remote sensing 
    - data science 
  affiliation:
    - The Alan Turing Institute
---
```

Linked to the issue [#109](https://github.com/alan-turing-institute/environmental-ds-book/issues/109) in the EDS book repository.
