### ISSUE TITLE
Adding the Climatematch Academy Site

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/projectpythia.github.io#292]
Make sure the following items are specified :

- `url`
- `title`
- `description`
- `authors` (please credit the creators of the resource in at least one method (`name`, `institution`, `institution_url`, or `email`)
- `tag` (at least one tag is required, this helps users access the link by searching via the relevant `packages`, `formats`, or `domains`)

```yaml
---
url: 'https://academy.climatematch.io/'
thumbnail: 'https://lh4.googleusercontent.com/RlYcZK0tFeTwk3dpOMkNg7N5eIP9YdgaY7hhvuYkhT9n1C-rN9SGUQFzU7b_QN5oTF75k1sEviXgEqj8wEfka4_7gE4157VbKl-0AGrwe7CZ3g9cBV78MQUvbPgdDrdWZrSWL6oGecSWYEAFGFNq6biwdZoC6o-58wYspRvxeuBc5ByJt0MaGQ=w1280' 
title: 'ClimateMatch Academy'
description: 'Climatematch Academy (CMA) is a wide-reaching, inclusive and approachable program aimed to introduce computational methods for climate science. The existing climate science research community severely underrepresents the global population that will be impacted by climate change. CMA strives to create a globally diverse climate sciences community, trained on cutting edge techniques to access and analyze open-source modeled and observational climate data. '
authors:
  - institution: Climatematch Team
    intution_url: https://academy.climatematch.io/about/team
tags:
  formats:
    - course
  domains:
    - climate
  affiliation:
    - neuromatch
    - pythia
---
```
