### ISSUE TITLE
Add `xbatcher` machine learning cookbook to resource gallery

### ISSUE THREAD

**Issue by cmdupuis3** [ProjectPythia/projectpythia.github.io#321]
Hi all! I wanted to get the submission process started, but for now, the repo linked here is only a draft.

```yaml
---
url: 'https://github.com/cmdupuis3/xbatcher-ML-1-cookbook' # The URL link to the resource you are submitting.
thumbnail: '' # The URL link to the thumbnail image associated with this resource.
title: 'Using `xbatcher` with Machine Learning Workflows (part 1)' # The title of the resource.
description: 'An end-to-end tutorial on how to use the [`xbatcher`](https://xbatcher.readthedocs.io/en/latest/) package with a straightforward convolutional neural network in Keras/Tensorflow.' # A brief description of the resource.
authors: # Mulitiple authors are supported, add each author separately.
  - name: 'Christopher Dupuis' # The name of the first author.
    institution: '' # The institution of the authors / first author (more appropriate than name if a large team worked on the resource).
    institution_url: '' # The URL link to the institution website.
    email: '' # The author's email, if publically available.
  - name: 'Anirban Sinha' # The name of the second+ author.
    institution: ''
    institution_url: ''
    email: ''
  - name: 'Ryan Abernathey' # The name of the second+ author.
    institution: ''
    institution_url: ''
    email: ''
tags: # Replace or delete the "unspecified" tag for each section with keywords associated with the resource. Multi-word tags should be entered with a space between the words (i.e. not joined with a `-`).
  packages:
    - xbatcher # List each Python package associated with this resource on a separate line (each entry on a new line, starting with a `-`).
    - tensorflow
    - keras
  formats:
    - tutorial # List the formats this resource takes. Currently used format tags include: book, course, documentation, gallery, tutorial, and video (but you may submit an entirely new tag if these do not best suit the resource).
  domains:
    - machine learning # List the domains associated with this resource so users may sort by areas of interest (e.g. remote sensing).
    - oceanography
    - software engineering
  affiliation:
    - M2LInES # List of the affiliated projects or organizations associated with this resource.
    - LEAP
    - Columbia University
    - Lamont-Doherty Earth Observatory
---
```
