### ISSUE TITLE
A guide to analyze and plot Earth Science data for Scientist of all programming skill levels

### ISSUE THREAD

**Issue by mpn21** [ProjectPythia/projectpythia.github.io#335]
Make sure the following items are specified :

- `url`
- `title`
- `description`
- `authors` (please credit the creators of the resource in at least one method (`name`, `institution`, `institution_url`, or `email`)
- `tag` (at least one tag is required, this helps users access the link by searching via the relevant `packages`, `formats`, or `domains`)

```yaml
---
url: '' # [The URL link to the resource you are submitting.](https://ploting-earth-science-data.web.app/)
thumbnail: '' # 
title: '' # A guide to analyze and plot Earth Science data for Scientist of all programming skill levels
description: '' # A guide to analyze and plot L-1 data product using CYGNSS mission as an example. Several examples are provided in the report. The URL link provided is a demostration of the project which was compiled using Jupyter Notebook. The Notebook file and  GitHub repository can be made available if projectpythia deem this project useful for the Earth Science Community. 
authors: # Mulitiple authors are supported, add each author separately.
  - name: '' # The name of the first author.
    institution: '' # Misssissippi State University
    institution_url: '' # www.msstate.edu
    email: '' # mpn21msstate@gmail.com
  - name: '' # The name of the second+ author.
    institution: ''
    institution_url: ''
    email: ''
tags: # "CGYNSS" "Cartopy" "Jupyter Notebook"
  packages:
    - unspecified # "Cartopy", "xarray", "numpy", matplotlib", "netCDF4"
  formats:
  domains: remote sensing
---
```

ProjectPythia,

I would love to the opportunity to contribute to the community and hope that my instruction set would be useful and acceptable. The project is developed using Jyputer Notebook and exported to HTML. Futhermore, I have posted the HTML file on a static web given below.

hyperlink:
https://ploting-earth-science-data.web.app/

I have been using Cartopy for years and I want to pay tribute to those that created this tool. The best method I know to pay tribute to the developers is to share my write up with the community. Please let me know if this topic is acceptable, any feedback would be greatly appreicated. 

Very Respectfully,

Michael Nguyen
