### ISSUE TITLE
PO.DAAC Cookbook

### ISSUE THREAD

**Issue by cassienickles** [ProjectPythia/projectpythia.github.io#366]
Make sure the following items are specified :

- `url`
- `title`
- `description`
- `authors` (please credit the creators of the resource in at least one method (`name`, `institution`, `institution_url`, or `email`)
- `tag` (at least one tag is required, this helps users access the link by searching via the relevant `packages`, `formats`, or `domains`)

```yaml
---
url: 'https://podaac.github.io/tutorials/' # The URL link to the resource you are submitting.
thumbnail: 'https://github.com/podaac/tutorials/blob/master/images/podaac_cookbook_thumbnail.png' # The URL link to the thumbnail image associated with this resource.
title: 'The PO.DAAC Cookbook' # The title of the resource.
description: 'A place to find NASA ocean, climate, and surface water data recipes and tutorials for the Physical Oceanography Distributed Active Archive Center (PO.DAAC) datasets, tools & services!' # A brief description of the resource.
authors: # Mulitiple authors are supported, add each author separately.
  - name: 'PO.DAAC Team' # The name of the first author.
    affiliation: 'Jet Propulsion Laboratory, California Institute of Technology' # The institution of the authors / first author (more appropriate than name if a large team worked on the resource).
    affiliation_url: 'https://www.jpl.nasa.gov/' # The URL link to the institution website.
    email: '' # The author's email, if publically available.
  - name: '' # The name of the second+ author.
    affiliation: ''
    affiliation_url: ''
    email: ''
tags: # Replace or delete the "unspecified" tag for each section with keywords associated with the resource. Multi-word tags should be entered with a space between the words (i.e. not joined with a `-`).
  packages:
    - earthaccess # List each Python package associated with this resource on a separate line (each entry on a new line, starting with a `-`).
    - xarray
  formats:
    - book # List the formats this resource takes. Currently used format tags include: book, course, documentation, gallery, tutorial, and video (but you may submit an entirely new tag if these do not best suit the resource).
    - tutorial
  domains:
    - remote sensing # List the domains associated with this resource so users may sort by areas of interest (e.g. remote sensing).
    - oceanography
    - hydrology
  affiliation:
    - Physical Oceanography Distributed Active Archive Center (PO.DAAC) # List of the affiliated projects or organizations associated with this resource.
    - Jet Propulsion Laboratory, California Institute of Technology
---
```

EDIT: Trigger the submission workflow.
