### ISSUE TITLE
Link to Herbie documentation

### ISSUE THREAD

**Issue by blaylockbk** [ProjectPythia/projectpythia.github.io#397]
Hi Pythia team! I enjoyed your session at AMS in Baltimore. Project Pythia is a great resource I have pointed many people to. 

I didn't get a chance to talk afterwards, but I wondered if you would be interested in adding a link to the Herbie documentation and repo. I gave this [presentation](https://ams.confex.com/ams/104ANNUAL/meetingapp.cgi/Paper/429567) on the Herbie Python package at AMS. I've been surprised at the number of people who use Herbie, especially people outside the atmospheric sciences domain who need to access and use NWP data.

Thanks for considering this linking to this resource.

```yaml
---
url: 'https://herbie.readthedocs.io/'
thumbnail: 'https://herbie.readthedocs.io/en/stable/_static/Herbie-logo.png'
title: 'Herbie: Retrieve NWP Model Data'
description: 'Herbie is a python package that downloads recent and archived numerical weather prediction (NWP) model output from different cloud archive sources. Its most popular capability is to download HRRR model data. NWP data in the GRIB2 format can be read with xarray+cfgrib.'
authors:
  - name: 'Brian Blaylock'
    affiliation: 'n/a'
    affiliation_url: 'n/a'
    email: 'n/a'
tags: 
  packages:
    - xarray
    - cfgrib
  formats:
    - documentation
    - tutorial
  domains:
    - Atmospheric Science
    - Numerical Weather Prediction
  affiliation:
    - unspecified
---
```
