### ISSUE TITLE
Link the Herbie documentation (one more time)

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/projectpythia.github.io#437]
Make sure the following items are specified :

- `url`
- `title`
- `description`
- `authors` (please credit the creators of the resource in at least one method (`name`, `affiliation`, `affiliation_url`, or `email`)
- `tag` (at least one tag is required, this helps users access the link by searching via the relevant `packages`, `formats`, or `domains`)

```yaml
---
url: 'https://herbie.readthedocs.io/' # The URL link to the resource you are submitting.
thumbnail: 'https://herbie.readthedocs.io/en/stable/_static/Herbie-logo.png' # The URL link to the thumbnail image associated with this resource.
title: 'Herbie: Retrieve NWP Model Data' # The title of the resource.
description: 'Herbie is a python package that downloads recent and archived numerical weather prediction (NWP) model output from different cloud archive sources. Its most popular capability is to download HRRR model data. NWP data in the GRIB2 format can be read with xarray+cfgrib.' # A brief description of the resource.
authors: # Mulitiple authors are supported, add each author separately.
  - name: 'Brian Blaylock' # The name of the first author.
    affiliation: 'n/a' # The affiliation of the authors / first author (more appropriate than name if a large team worked on the resource).
    affiliation_url: 'n/a' # The URL link to the affiliation website.
    email: 'n/a' # The author's email, if publically available.
tags: # Replace or delete the "unspecified" tag for each section with keywords associated with the resource. Multi-word tags should be entered with a space between the words (i.e. not joined with a `-`).
  packages:
    - xarray # List each Python package associated with this resource on a separate line (each entry on a new line, starting with a `-`).
    - cfgrib
  formats:
    - documentation # List the formats this resource takes. Currently used format tags include: book, course, documentation, gallery, tutorial, and video (but you may submit an entirely new tag if these do not best suit the resource).
    - tutorial
  domains:
    - Atmospheric Science # List the domains associated with this resource so users may sort by areas of interest (e.g. remote sensing).
    - Numerical Weather Prediction
---
```

One more attempt to repeat #397
