### ISSUE TITLE
Bialegdz 

### ISSUE THREAD

**Issue by Bramwelian** [ProjectPythia/projectpythia.github.io#449]
Make sure the following items are specified :

- `url`
- `title`
- `description`
- `authors` (please credit the creators of the resource in at least one method (`BramwelAuku`, `affiliation`, `affiliation_url`, or `ianbramwel573 @gmail.com`)
- `tag` (at least one tag is required, this helps users access the link by searching via the relevant `packages`, `formats`, or `domains`)

```yaml
---
url: '' # The URL link to the resource you are submitting.
thumbnail: '' # The URL link to the thumbnail image associated with this resource.
title: '' # The title of the resource.
description: '' # A brief description of the resource.
authors: # Mulitiple authors are supported, add each author separately.
  - name: '' # The name of the first author.
    affiliation: '' # The affiliation of the authors / first author (more appropriate than name if a large team worked on the resource).
    affiliation_url: '' # The URL link to the affiliation website.
    email: '' # The author's email, if publically available.
  - name: '' # The name of the second+ author.
    affiliation: ''
    affiliation_url: ''
    email: ''
tags: # Replace or delete the "unspecified" tag for each section with keywords associated with the resource. Multi-word tags should be entered with a space between the words (i.e. not joined with a `-`).
  packages:
    - unspecified # List each Python package associated with this resource on a separate line (each entry on a new line, starting with a `-`).
  formats:
    - unspecified # List the formats this resource takes. Currently used format tags include: book, course, documentation, gallery, tutorial, and video (but you may submit an entirely new tag if these do not best suit the resource).
  domains:
    - unspecified # List the domains associated with this resource so users may sort by areas of interest (e.g. remote sensing).
  affiliation:
    - unspecified # List of the affiliated projects or organizations associated with this resource.
---
```
