### ISSUE TITLE
Update resource gallery: Add Uxarray 

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/projectpythia.github.io#455]
```yaml
---
url: 'https://uxarray.readthedocs.io/'
thumbnail: 'https://raw.githubusercontent.com/UXARRAY/uxarray/921dd8f42f661692f0cec170ee5c7dbedb294237/docs/_static/images/logos/uxarray_logo_v_dark.svg'
title: 'UXarray'
description: 'Xarray extension for unstructured climate and global weather data' # A brief description of the resource.
authors:
- name: 'Aaron Zedwick'
  affiliation: 'Liberty University'
  affiliation_url: 'https://www.liberty.edu/'
- name: 'Amber Chen'
- name: 'Anissa Zacharias'
  affiliation: 'NSF National Center for Atmospheric Research'
  affiliation_url: 'https://ncar.ucar.edu/'
- name: 'Brian Medeiros'
  affiliation: 'NSF National Center for Atmospheric Research'
  affiliation_url: 'https://ncar.ucar.edu/'
- name: 'Colin Zarzycki'
  affiliation: 'The Pennsylvania State University'
  affiliation_url: 'https://www.psu.edu/'
- name: 'Hongyu Chen'
  affiliation: 'University of California Davis'
  affiliation_url: 'https://www.ucdavis.edu/'
- name: 'Ian Franda'
  affiliation: 'University of Wisconsin-Madison'
  affiliation_url: 'https://www.wisc.edu/'
- name: 'John Clyne'
  affiliation: 'NSF National Center for Atmospheric Research'
  affiliation_url: 'https://ncar.ucar.edu/'
- name: 'Michaela Sizemore'
  affiliation: National Renewable Energy Laboratory
  affiliation_url: https://www.nrel.gov/
- name: 'Orhan Eroglu'
  affiliation: 'NSF National Center for Atmospheric Research'
  affiliation_url: 'https://ncar.ucar.edu/'
  email: 'oero@ucar.edu'
- name: 'Paul Ullrich'
  affiliation: 'University of California Davis'
  affiliation_url: 'https://www.ucdavis.edu/'
- name: 'Philip Chmielowiec'
  affiliation: 'NSF National Center for Atmospheric Research'
  affiliation_url: 'https://ncar.ucar.edu/'
- name: 'Rachel Tam'
  affiliation: 'University of Illinois Urbana-Champaign'
  affiliation_url: 'https://illinois.edu/'
- name: 'Rajeev Jain'
  affiliation: 'Argonne National Laboratory'
  affiliation_url: 'https://www.anl.gov/'
- name: 'Robert Jacob'
  affiliation: 'Argonne National Laboratory'
  affiliation_url: 'https://www.anl.gov/'
tags:
  packages:
    - xarray
    - dask
    - numba
    - numpy
    - spatialpandas
    - datashader
    - holoviews
    - matplotlib
  formats:
    - documentation
    - tutorial
  domains:
    - Unstructured Grids
    - Data Analysis
    - Data Visualization
    - Atmospheric Science
    - Climate Science
  affiliation:
    - Pangeo
    - Raijin
    - SEATS
---
```
