### ISSUE TITLE
This is a test

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/projectpythia.github.io#89]
Checklist of required entries:

- [x] `url` is specified
- [ ] `title` is specified
- [ ] `description` is specified

**Note**:

- The thumbnail can be a url to a direct image link.

```yaml
---
url: ''
thumbnail: ''
title: ''
description: ''
authors:
  - name: ''
    affiliation: ''
    affiliation_url: ''
    email: ''
  - name: ''
    affiliation: ''
    affiliation_url: ''
    email: ''
---

```
