### ISSUE TITLE
Add `Python-for-Earth-Science-Students` to the external links gallery

### ISSUE THREAD

**Issue by andersy005** [ProjectPythia/projectpythia.github.io#90]
Addresses https://github.com/ProjectPythia/projectpythia.github.io/discussions/84

Checklist of required entries:

- [x] `url` is specified
- [x] `title` is specified
- [x] `description` is specified

**Note**:

- The thumbnail can be a url to a direct image link.

```yaml
---
url: 'https://nbviewer.jupyter.org/github/ltauxe/Python-for-Earth-Science-Students/tree/master/'
thumbnail: ''
title: 'Python Programming for Earth Science Students'
description: 'Python Programming for Earth Science Students'
authors:
  - name: 'Lisa Tauxe'
    affiliation: 'Scripps Institution of Oceanography'
    affiliation_url: 'https://scripps.ucsd.edu/'
    email: 'ltauxe@ucsd.edu'
  - name: 'Hanna Asefaw'
    affiliation: ''
    affiliation_url: ''
    email: 'hasefaw@ucsd.edu'
  - name: 'Brendan Cych'
    affiliation: ''
    affiliation_url: ''
    email: 'bcych@ucsd.edu'

tags:
  formats:
    - tutorial 
  packages:
    - pure python
    - pandas
    - scipy
    - numpy
    - matplotlib

---
```
